import { Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "./globals.css";
import "./splash.css";

const geistSans = Geist({
  weight: ['400', '500', '700'],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  weight: ['400', '700'],
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo2 = Exo_2({
  weight: ['400', '700'],
  variable: "--font-exo-2",
  subsets: ["latin"],
});
export const metadata = {
  title: "Tailor That!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
